version: "3"

services:
  firebase-emulator:
    container_name: firebase-emulator
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - GCLOUD_PORJECT=${GCP_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=./sa.json
    volumes:
      - ./src/firebase/.config:/root/.config
      - ./src/firebase/firebase.json/:/root/firebase.json
      - ./src/firebase/firestore.rules/:/root/firebase.rules
      - ./src/firebase/storage.rules/:/root/storage.rules
      - ./src/firebase/.firebaserc/:/root/.firebaserc
      - ./sa.json:/root/sa.json # service account
    ports:
      - 4000:4000 # Emulator Suite UI
      - 5000:5000 # Firebase Hosting
      - 5001:5001 # Clound Functions
      - 8081:8081 # Cloud Firestore
      - 8085:8085 # Cloud Pub/Sub
      - 8080:8080 # Firestore
      - 9000:9000 # Realtime Database
      - 9099:9099 # Auth
      - 9199:9199 # Storage
    working_dir: /root/
    # command: firebase emulators:start
    tty: true
